spring:
  profiles:
    active: local
  jpa:
    show-sql: true
    generate-ddl: true
server:
  servlet:
    context-path: /api/v1
jwt:
  secret: 8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds
oauth:
  kakao:
    authenticationUrl: https://kauth.kakao.com/oauth/token
    authorizationUrl: https://kapi.kakao.com/v2/user/me
    grantType: authorization_code
    clientId: 899719034b2557a7c9b9ed80e93b5afd
