spring:
  datasource:
    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S08P22C105?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: S08P22C105@stg-yswa-kr-practice-db-master.mariadb.database.azure.com
    password: UVatA2MtuY
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none

file:
  image:
    path: /app/
oauth:
  kakao:
    redirectUri: https://j8c105.p.ssafy.io/

OPENVIDU_URL: https://j8c105.p.ssafy.io:4443